<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>R in the CWRS</title>
  <meta name="description" content="A collection of R lessons for CWRS projects">
  <meta name="generator" content="bookdown 0.5 and GitBook 2.6.7">

  <meta property="og:title" content="R in the CWRS" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A collection of R lessons for CWRS projects" />
  <meta name="github-repo" content="paleolimbot/r4cwrs" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="R in the CWRS" />
  
  <meta name="twitter:description" content="A collection of R lessons for CWRS projects" />
  

<meta name="author" content="The R Programming Group at the CWRS">


<meta name="date" content="2017-09-01">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="using-rstudio-projects.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R for the CWRS</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="1" data-path="basic-r.html"><a href="basic-r.html"><i class="fa fa-check"></i><b>1</b> Basic R</a><ul>
<li class="chapter" data-level="1.1" data-path="basic-r.html"><a href="basic-r.html#prerequisites"><i class="fa fa-check"></i><b>1.1</b> Prerequisites</a></li>
<li class="chapter" data-level="1.2" data-path="basic-r.html"><a href="basic-r.html#expressions-and-variables"><i class="fa fa-check"></i><b>1.2</b> Expressions and Variables</a></li>
<li class="chapter" data-level="1.3" data-path="basic-r.html"><a href="basic-r.html#functions"><i class="fa fa-check"></i><b>1.3</b> Functions</a></li>
<li class="chapter" data-level="1.4" data-path="basic-r.html"><a href="basic-r.html#vectors"><i class="fa fa-check"></i><b>1.4</b> Vectors</a></li>
<li class="chapter" data-level="1.5" data-path="basic-r.html"><a href="basic-r.html#indexing"><i class="fa fa-check"></i><b>1.5</b> Indexing</a></li>
<li class="chapter" data-level="1.6" data-path="basic-r.html"><a href="basic-r.html#using-the-script-editor"><i class="fa fa-check"></i><b>1.6</b> Using the Script Editor</a></li>
<li class="chapter" data-level="1.7" data-path="basic-r.html"><a href="basic-r.html#excercises"><i class="fa fa-check"></i><b>1.7</b> Excercises</a></li>
<li class="chapter" data-level="1.8" data-path="basic-r.html"><a href="basic-r.html#summary"><i class="fa fa-check"></i><b>1.8</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="working-with-tables-using-the-tidyverse.html"><a href="working-with-tables-using-the-tidyverse.html"><i class="fa fa-check"></i><b>2</b> Working with Tables using the Tidyverse</a><ul>
<li class="chapter" data-level="2.1" data-path="working-with-tables-using-the-tidyverse.html"><a href="working-with-tables-using-the-tidyverse.html#prerequisites-1"><i class="fa fa-check"></i><b>2.1</b> Prerequisites</a></li>
<li class="chapter" data-level="2.2" data-path="working-with-tables-using-the-tidyverse.html"><a href="working-with-tables-using-the-tidyverse.html#viewing-a-data-frame"><i class="fa fa-check"></i><b>2.2</b> Viewing a Data Frame</a></li>
<li class="chapter" data-level="2.3" data-path="working-with-tables-using-the-tidyverse.html"><a href="working-with-tables-using-the-tidyverse.html#selecting-columns"><i class="fa fa-check"></i><b>2.3</b> Selecting Columns</a><ul>
<li class="chapter" data-level="2.3.1" data-path="working-with-tables-using-the-tidyverse.html"><a href="working-with-tables-using-the-tidyverse.html#excercises-1"><i class="fa fa-check"></i><b>2.3.1</b> Excercises</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="working-with-tables-using-the-tidyverse.html"><a href="working-with-tables-using-the-tidyverse.html#filtering-rows"><i class="fa fa-check"></i><b>2.4</b> Filtering Rows</a><ul>
<li class="chapter" data-level="2.4.1" data-path="working-with-tables-using-the-tidyverse.html"><a href="working-with-tables-using-the-tidyverse.html#exercises"><i class="fa fa-check"></i><b>2.4.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="working-with-tables-using-the-tidyverse.html"><a href="working-with-tables-using-the-tidyverse.html#selecting-and-filtering"><i class="fa fa-check"></i><b>2.5</b> Selecting and Filtering</a><ul>
<li class="chapter" data-level="2.5.1" data-path="working-with-tables-using-the-tidyverse.html"><a href="working-with-tables-using-the-tidyverse.html#exercises-1"><i class="fa fa-check"></i><b>2.5.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="working-with-tables-using-the-tidyverse.html"><a href="working-with-tables-using-the-tidyverse.html#the-pipe"><i class="fa fa-check"></i><b>2.6</b> The Pipe (%&gt;%)</a><ul>
<li class="chapter" data-level="2.6.1" data-path="working-with-tables-using-the-tidyverse.html"><a href="working-with-tables-using-the-tidyverse.html#exercises-2"><i class="fa fa-check"></i><b>2.6.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="working-with-tables-using-the-tidyverse.html"><a href="working-with-tables-using-the-tidyverse.html#summarising-a-data-frame"><i class="fa fa-check"></i><b>2.7</b> Summarising A Data Frame</a></li>
<li class="chapter" data-level="2.8" data-path="working-with-tables-using-the-tidyverse.html"><a href="working-with-tables-using-the-tidyverse.html#excercises-2"><i class="fa fa-check"></i><b>2.8</b> Excercises</a></li>
<li class="chapter" data-level="2.9" data-path="working-with-tables-using-the-tidyverse.html"><a href="working-with-tables-using-the-tidyverse.html#summary-1"><i class="fa fa-check"></i><b>2.9</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="creating-visualizations-using-ggplot.html"><a href="creating-visualizations-using-ggplot.html"><i class="fa fa-check"></i><b>3</b> Creating Visualizations using ggplot</a><ul>
<li class="chapter" data-level="3.1" data-path="creating-visualizations-using-ggplot.html"><a href="creating-visualizations-using-ggplot.html#prerequisites-2"><i class="fa fa-check"></i><b>3.1</b> Prerequisites</a></li>
<li class="chapter" data-level="3.2" data-path="creating-visualizations-using-ggplot.html"><a href="creating-visualizations-using-ggplot.html#using-ggplot"><i class="fa fa-check"></i><b>3.2</b> Using ggplot</a></li>
<li class="chapter" data-level="3.3" data-path="creating-visualizations-using-ggplot.html"><a href="creating-visualizations-using-ggplot.html#summary-2"><i class="fa fa-check"></i><b>3.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="preparing-and-loading-your-data-into-r.html"><a href="preparing-and-loading-your-data-into-r.html"><i class="fa fa-check"></i><b>4</b> Preparing and Loading your data into R</a><ul>
<li class="chapter" data-level="4.1" data-path="preparing-and-loading-your-data-into-r.html"><a href="preparing-and-loading-your-data-into-r.html#prerequisites-3"><i class="fa fa-check"></i><b>4.1</b> Prerequisites</a></li>
<li class="chapter" data-level="4.2" data-path="preparing-and-loading-your-data-into-r.html"><a href="preparing-and-loading-your-data-into-r.html#preparing-data"><i class="fa fa-check"></i><b>4.2</b> Preparing data</a></li>
<li class="chapter" data-level="4.3" data-path="preparing-and-loading-your-data-into-r.html"><a href="preparing-and-loading-your-data-into-r.html#loading-data"><i class="fa fa-check"></i><b>4.3</b> Loading data</a></li>
<li class="chapter" data-level="4.4" data-path="preparing-and-loading-your-data-into-r.html"><a href="preparing-and-loading-your-data-into-r.html#cleaning-data"><i class="fa fa-check"></i><b>4.4</b> Cleaning data</a></li>
<li class="chapter" data-level="4.5" data-path="preparing-and-loading-your-data-into-r.html"><a href="preparing-and-loading-your-data-into-r.html#summary-3"><i class="fa fa-check"></i><b>4.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="using-rstudio-projects.html"><a href="using-rstudio-projects.html"><i class="fa fa-check"></i><b>5</b> Using RStudio Projects</a><ul>
<li class="chapter" data-level="5.1" data-path="using-rstudio-projects.html"><a href="using-rstudio-projects.html#prerequisites-4"><i class="fa fa-check"></i><b>5.1</b> Prerequisites</a></li>
<li class="chapter" data-level="5.2" data-path="using-rstudio-projects.html"><a href="using-rstudio-projects.html#projects"><i class="fa fa-check"></i><b>5.2</b> Projects</a></li>
<li class="chapter" data-level="5.3" data-path="using-rstudio-projects.html"><a href="using-rstudio-projects.html#creating-a-new-project"><i class="fa fa-check"></i><b>5.3</b> Creating a new project</a></li>
<li class="chapter" data-level="5.4" data-path="using-rstudio-projects.html"><a href="using-rstudio-projects.html#organizing-a-project"><i class="fa fa-check"></i><b>5.4</b> Organizing a project</a></li>
<li class="chapter" data-level="5.5" data-path="using-rstudio-projects.html"><a href="using-rstudio-projects.html#why-use-a-project"><i class="fa fa-check"></i><b>5.5</b> Why use a project?</a></li>
<li class="chapter" data-level="5.6" data-path="using-rstudio-projects.html"><a href="using-rstudio-projects.html#summary-4"><i class="fa fa-check"></i><b>5.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="computing-statistics-in-r.html"><a href="computing-statistics-in-r.html"><i class="fa fa-check"></i><b>6</b> Computing statistics in R</a><ul>
<li class="chapter" data-level="6.1" data-path="computing-statistics-in-r.html"><a href="computing-statistics-in-r.html#prerequisites-5"><i class="fa fa-check"></i><b>6.1</b> Prerequisites</a></li>
<li class="chapter" data-level="6.2" data-path="computing-statistics-in-r.html"><a href="computing-statistics-in-r.html#correlation-and-linear-regression"><i class="fa fa-check"></i><b>6.2</b> Correlation and Linear Regression</a><ul>
<li class="chapter" data-level="6.2.1" data-path="computing-statistics-in-r.html"><a href="computing-statistics-in-r.html#test-data"><i class="fa fa-check"></i><b>6.2.1</b> Test Data</a></li>
<li class="chapter" data-level="6.2.2" data-path="computing-statistics-in-r.html"><a href="computing-statistics-in-r.html#graphical-test"><i class="fa fa-check"></i><b>6.2.2</b> Graphical Test</a></li>
<li class="chapter" data-level="6.2.3" data-path="computing-statistics-in-r.html"><a href="computing-statistics-in-r.html#the-pearson-product-moment-correlation-coefficient-r"><i class="fa fa-check"></i><b>6.2.3</b> The Pearson product-moment correlation coefficient (<em>r</em>)</a></li>
<li class="chapter" data-level="6.2.4" data-path="computing-statistics-in-r.html"><a href="computing-statistics-in-r.html#spearman-rho-or-rs"><i class="fa fa-check"></i><b>6.2.4</b> Spearman <span class="math inline">\(\rho\)</span> or <em>r<sub>s</sub></em></a></li>
<li class="chapter" data-level="6.2.5" data-path="computing-statistics-in-r.html"><a href="computing-statistics-in-r.html#linear-regression"><i class="fa fa-check"></i><b>6.2.5</b> Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="computing-statistics-in-r.html"><a href="computing-statistics-in-r.html#significant-differences-with-two-groups"><i class="fa fa-check"></i><b>6.3</b> Significant differences with two groups</a><ul>
<li class="chapter" data-level="6.3.1" data-path="computing-statistics-in-r.html"><a href="computing-statistics-in-r.html#the-t-test"><i class="fa fa-check"></i><b>6.3.1</b> The t-test</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="computing-statistics-in-r.html"><a href="computing-statistics-in-r.html#statistical-test-3"><i class="fa fa-check"></i><b>6.4</b> Statistical Test</a><ul>
<li class="chapter" data-level="6.4.1" data-path="computing-statistics-in-r.html"><a href="computing-statistics-in-r.html#paired-t-test"><i class="fa fa-check"></i><b>6.4.1</b> Paired t-test</a></li>
<li class="chapter" data-level="6.4.2" data-path="computing-statistics-in-r.html"><a href="computing-statistics-in-r.html#wilcox-rank-sum-test"><i class="fa fa-check"></i><b>6.4.2</b> Wilcox Rank Sum Test</a></li>
<li class="chapter" data-level="6.4.3" data-path="computing-statistics-in-r.html"><a href="computing-statistics-in-r.html#mann-whitney-test"><i class="fa fa-check"></i><b>6.4.3</b> Mann-Whitney Test</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="computing-statistics-in-r.html"><a href="computing-statistics-in-r.html#significant-differences-with-more-than-two-groups"><i class="fa fa-check"></i><b>6.5</b> Significant differences with more than two groups</a><ul>
<li class="chapter" data-level="6.5.1" data-path="computing-statistics-in-r.html"><a href="computing-statistics-in-r.html#the-anova-test"><i class="fa fa-check"></i><b>6.5.1</b> The ANOVA test</a></li>
<li class="chapter" data-level="6.5.2" data-path="computing-statistics-in-r.html"><a href="computing-statistics-in-r.html#graphical-test-2"><i class="fa fa-check"></i><b>6.5.2</b> Graphical Test</a></li>
<li class="chapter" data-level="6.5.3" data-path="computing-statistics-in-r.html"><a href="computing-statistics-in-r.html#krustal-wallis-rank-sum-test"><i class="fa fa-check"></i><b>6.5.3</b> Krustal-Wallis Rank Sum Test</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="computing-statistics-in-r.html"><a href="computing-statistics-in-r.html#summary-5"><i class="fa fa-check"></i><b>6.6</b> Summary</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R in the CWRS</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="computing-statistics-in-r" class="section level1">
<h1><span class="header-section-number">Chapter 6</span> Computing statistics in R</h1>
<p>Intro</p>
<div id="prerequisites-5" class="section level2">
<h2><span class="header-section-number">6.1</span> Prerequisites</h2>
<p>The prerequisites for this tutorial are the <code>tidyverse</code> and <code>broom</code> packages. If these packages aren’t installed, you’ll have to install them using <code>install.packages()</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">install.packages</span>(<span class="st">&quot;tidyverse&quot;</span>) <span class="co"># will also install the broom package</span></code></pre></div>
<p>Load the packages when you’re done! If there are errors, you may have not installed the above packages correctly!</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(rclimateca)
<span class="kw">library</span>(broom)</code></pre></div>
<p>Finally, you will need to obtain the sample data…</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">climate_data &lt;-<span class="st"> </span><span class="kw">getClimateData</span>(<span class="kw">c</span>(<span class="dv">27141</span>, <span class="dv">6354</span>), <span class="dt">year =</span> <span class="dv">2000</span>:<span class="dv">2003</span>,
                               <span class="dt">nicenames =</span> <span class="ot">TRUE</span>) %&gt;%
<span class="st">  </span><span class="kw">left_join</span>(ecclimatelocs %&gt;%<span class="st"> </span><span class="kw">select</span>(<span class="dt">station_name =</span> Name, <span class="dt">stationid =</span> <span class="st">`</span><span class="dt">Station ID</span><span class="st">`</span>),
            <span class="dt">by =</span> <span class="st">&quot;stationid&quot;</span>)</code></pre></div>
</div>
<div id="correlation-and-linear-regression" class="section level2">
<h2><span class="header-section-number">6.2</span> Correlation and Linear Regression</h2>
<p>Tests for correlation of two variables test whether or not a relationship exists between the two variables (i.e., can any of the variance of one variable be explained by variance in the other). This is often done to test association between two parameters when these measurements are paired. In our example, we will test the corellation between mean monthly temperature and total monthly precipitation, to ascertain whether or not a statistically significant relationship exists between the two.</p>
<div id="test-data" class="section level3">
<h3><span class="header-section-number">6.2.1</span> Test Data</h3>
<p>Correlation tests all require a data frame with one column for the x variable and one column for the y variable. It is often useful to keep other qualifying variables that give context to each observation, but are not required by the test. In our case, the x variable will be <code>meantemp</code> and the y variable will be <code>totalprecip</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">correlation_test_data &lt;-<span class="st"> </span>climate_data %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(station_name, year, month, meantemp, totalprecip)
correlation_test_data</code></pre></div>
<pre><code>## # A tibble: 96 x 5
##        station_name  year month meantemp totalprecip
##               &lt;chr&gt; &lt;int&gt; &lt;int&gt;    &lt;dbl&gt;       &lt;dbl&gt;
##  1 KENTVILLE CDA CS  2000     1     -4.2       182.2
##  2 KENTVILLE CDA CS  2000     2     -2.6        10.7
##  3 KENTVILLE CDA CS  2000     3      1.6       116.4
##  4 KENTVILLE CDA CS  2000     4      6.4        89.1
##  5 KENTVILLE CDA CS  2000     5     10.0        58.0
##  6 KENTVILLE CDA CS  2000     6     16.4        46.0
##  7 KENTVILLE CDA CS  2000     7     18.8        72.4
##  8 KENTVILLE CDA CS  2000     8     19.2        36.6
##  9 KENTVILLE CDA CS  2000     9     14.6        58.4
## 10 KENTVILLE CDA CS  2000    10      9.9       197.6
## # ... with 86 more rows</code></pre>
</div>
<div id="graphical-test" class="section level3">
<h3><span class="header-section-number">6.2.2</span> Graphical Test</h3>
<p>A graphical test of the correlation of two variables is a biplot with one variable on the x-axis, and one variable on the y-axis. The variable on the x-axis should be the indepenent variable for the purposes of the test. This will look something like <code>ggplot(my_data_frame, x = independent_var, y = dependent_var)</code> followed by <code>geom_point()</code>. You can add a linear regression to the plot using <code>stat_smooth(method = lm)</code>. This will add the best-fit line whose slope and intercept we will calculate in the next section.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(correlation_test_data, <span class="kw">aes</span>(<span class="dt">x =</span> meantemp, <span class="dt">y =</span> totalprecip)) +
<span class="st">  </span><span class="kw">geom_point</span>() +
<span class="st">  </span><span class="kw">stat_smooth</span>(<span class="dt">method =</span> lm)</code></pre></div>
<pre><code>## Warning: Removed 2 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 2 rows containing missing values (geom_point).</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-60-1.png" width="672" /></p>
<p>Based on inspection of the biplot, you should be able to have a hunch as to whether or not a linear relationship exists between the two variables. In our case, it looks like there is a weak negative correlation between mean temperature and total preciptiation (i.e., the higher the mean temperature for a given month, the lower the total precipitation for the same month).</p>
</div>
<div id="the-pearson-product-moment-correlation-coefficient-r" class="section level3">
<h3><span class="header-section-number">6.2.3</span> The Pearson product-moment correlation coefficient (<em>r</em>)</h3>
<p>The Pearson product-moment correlation coefficient (usually known as the <em>r</em> value) is a test of how well a line of best fit is able to model the data (generally a standard least-squares linear regression). The coefficient ranges from -1 (perfect negative linear relationship) to +1 (perfect positive linear relationship). Generally the square of this value is reported (r<sup>2</sup>), and can be interpreted as “xx % of the variance in <code>y_variable</code> can be explained by the variance in <code>x_variable</code>”. There is no statistical way to test how good the linear relationship is, but it is possible to test that the coefficient is not equal to zero (i.e., it is possible to reject the notion that there <code>x_variable</code> and <code>y_variable</code> have no linear relationship).</p>
<div id="assumptions" class="section level4">
<h4><span class="header-section-number">6.2.3.1</span> Assumptions</h4>
<p>The Pearson product-moment correlation coefficient assumes that <code>x_variable</code> and <code>y_variable</code> are normally distributed.</p>
</div>
<div id="statistical-test" class="section level4">
<h4><span class="header-section-number">6.2.3.2</span> Statistical Test</h4>
<p>Calculating the <em>r</em> value and associated p-value involves a call to <code>cor.test()</code> with <code>method = &quot;pearson&quot;</code>, followed by a call to <code>tidy()</code> in the <strong>broom</strong> package to get the test results in the form of a data frame.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor.test</span>(~totalprecip +<span class="st"> </span>meantemp, <span class="dt">data =</span> correlation_test_data, 
         <span class="dt">method =</span> <span class="st">&quot;pearson&quot;</span>) %&gt;%
<span class="st">  </span><span class="kw">tidy</span>()</code></pre></div>
<pre><code>## # A tibble: 1 x 8
##     estimate statistic     p.value parameter   conf.low  conf.high
##        &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;     &lt;int&gt;      &lt;dbl&gt;      &lt;dbl&gt;
## 1 -0.3043945   -3.0651 0.002855764        92 -0.4775578 -0.1084673
## # ... with 2 more variables: method &lt;fctr&gt;, alternative &lt;fctr&gt;</code></pre>
<p>The <code>estimate</code> column contains the <em>r</em> value, which you could square to get the <em>r<sup>2</sup></em> value. The <code>p.value</code> column contains the p-value, which represents the probability that the two variables have no linear relationship. In our case, <code>totalprecip</code> and <code>meantemp</code> have a significant negative linear relationship (<em>p</em>=0.003).</p>
</div>
</div>
<div id="spearman-rho-or-rs" class="section level3">
<h3><span class="header-section-number">6.2.4</span> Spearman <span class="math inline">\(\rho\)</span> or <em>r<sub>s</sub></em></h3>
<p>The Spearman correlation coefficient (abbreviated <span class="math inline">\(\rho\)</span> or <em>r<sub>s</sub></em>) is a test of a one-to-one relationship between <code>x_variable</code> and <code>y_variable</code>, not necessarily linear. The test uses ranked values for <code>x_variable</code> and <code>y_variable</code>, so outliers are less of an issue than they are with the Pearson coefficient. Similar to the Perason coefficient, the <em>r<sub>s</sub></em> value varies from -1 (a perfect one-to-one negative relationship) to 1 (a perfect one-to-one positive relationship). Similar to the Pearson coefficient, it is only possible to test that the value is not equal to zero (i.e., i.e., it is possible to reject the notion that there <code>x_variable</code> and <code>y_variable</code> have no one-to-one relationship).</p>
<div id="assumptions-1" class="section level4">
<h4><span class="header-section-number">6.2.4.1</span> Assumptions</h4>
<p>The Spearman correlation coefficient does not make any assumptions about the distribution of <code>x_variable</code> or <code>y_variable</code>.</p>
</div>
<div id="statistical-test-1" class="section level4">
<h4><span class="header-section-number">6.2.4.2</span> Statistical Test</h4>
<p>Calculating the <em>r<sub>s</sub></em> value and associated p-value involves a call to <code>cor.test()</code> with <code>method = &quot;spearman&quot;</code>, followed by a call to <code>tidy()</code> in the <strong>broom</strong> package to get the test results in the form of a data frame.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor.test</span>(~totalprecip +<span class="st"> </span>meantemp, <span class="dt">data =</span> correlation_test_data, 
         <span class="dt">method =</span> <span class="st">&quot;spearman&quot;</span>) %&gt;%
<span class="st">  </span><span class="kw">tidy</span>()</code></pre></div>
<pre><code>## Warning in cor.test.default(x = c(182.2, 10.7, 116.4, 89.1, 58, 46, 72.4, :
## Cannot compute exact p-value with ties</code></pre>
<pre><code>## # A tibble: 1 x 5
##     estimate statistic     p.value                          method
##        &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;                          &lt;fctr&gt;
## 1 -0.3806479  191102.4 0.000153924 Spearman&#39;s rank correlation rho
## # ... with 1 more variables: alternative &lt;fctr&gt;</code></pre>
<p>The <code>estimate</code> column contains the <em>r<sub>s</sub></em> value, and the <code>p.value</code> column contains the p-value, which represents the probability that the two variables are not correlated. In our case, <code>totalprecip</code> and <code>meantemp</code> have a significant negative relationship (<em>p</em>&lt;0.001).</p>
</div>
</div>
<div id="linear-regression" class="section level3">
<h3><span class="header-section-number">6.2.5</span> Linear Regression</h3>
<p>Whereas a Pearson coefficient is meant to assess the quality of a linear relationship, linear regression is meant to determine the slope and intercept of that relationship in the form <span class="math inline">\(y = mx + b\)</span>, where <span class="math inline">\(y\)</span> is <code>y_variable</code>, and x is <code>x_variable</code>. By obtaining <span class="math inline">\(m\)</span> and <span class="math inline">\(b\)</span>, we can use <code>x_variable</code> to calculate <code>y_variable</code> for any value of <code>x_variable</code>.</p>
<div id="assumptions-2" class="section level4">
<h4><span class="header-section-number">6.2.5.1</span> Assumptions</h4>
<p>The standard linear regression (a least-squares regression) works best if both <code>x_variable</code> and <code>y_variable</code> are symmetrically distributed.</p>
</div>
<div id="statistical-test-2" class="section level4">
<h4><span class="header-section-number">6.2.5.2</span> Statistical Test</h4>
<p>Calculating the coefficients <span class="math inline">\(m\)</span> and <span class="math inline">\(b\)</span> for a linear regression involves a call to <code>lm()</code> with a formula <code>y_variable ~ x_variable</code> (note this is slightly different than for correlation testing) and <code>data = my_data_frame</code>. For our example, the call would look like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lm</span>(totalprecip ~<span class="st"> </span>meantemp, <span class="dt">data =</span> correlation_test_data) %&gt;%
<span class="st">  </span><span class="kw">tidy</span>()</code></pre></div>
<pre><code>## # A tibble: 2 x 5
##          term   estimate std.error statistic      p.value
##         &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt;
## 1 (Intercept) 101.080256  5.453909  18.53354 8.134131e-33
## 2    meantemp  -1.438531  0.469326  -3.06510 2.855764e-03</code></pre>
<p>The <code>term</code> column in the ouput refers to the name of the input column in the righthand side of the input formula, or “(Intercept)” for the intercept, and the <code>estimate</code> column refers to the coefficient itself. In the example, this means we can predict <code>totalprecip</code> using the (approximate) expression <code>-1.44 * meantemp + 101.08</code>.</p>
<p>In practice, we want to use the <code>predict()</code> function to do this math for us (because if we change some code above that alters which observations are used to create the regression, it will change the coefficient and intercept, and any code that relies on the hard-coded version will be incorrect). This is a three step process: first, save the result of <code>lm()</code> to a variable, then create a data frame with a column that has the same name as <code>x_variable</code>, then use <code>mutate()</code> to create a new column with the predictions from <code>predict()</code>. Note that we use a special trick in <code>mutate()</code> to pass the entire data frame to the <code>newdata</code> argument of <code>predict()</code> (the <code>.</code> represents the whole data frame as opposed to any particular column, which we can refer to by name within <code>mutate()</code>). For our example, we might be interested in the predicted total monthly precipitation values when the mean monthly temperature is 5, 10, 15, and 20 degrees.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">lm</span>(totalprecip ~<span class="st"> </span>meantemp, <span class="dt">data =</span> climate_data)
<span class="kw">tibble</span>(<span class="dt">meantemp =</span> <span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">20</span>)) %&gt;%
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">totalprecip_predicted =</span> <span class="kw">predict</span>(model, <span class="dt">newdata =</span> .))</code></pre></div>
<pre><code>## # A tibble: 4 x 2
##   meantemp totalprecip_predicted
##      &lt;dbl&gt;                 &lt;dbl&gt;
## 1        5              93.88760
## 2       10              86.69494
## 3       15              79.50229
## 4       20              72.30963</code></pre>
</div>
</div>
</div>
<div id="significant-differences-with-two-groups" class="section level2">
<h2><span class="header-section-number">6.3</span> Significant differences with two groups</h2>
<div id="the-t-test" class="section level3">
<h3><span class="header-section-number">6.3.1</span> The t-test</h3>
<p>The ANOVA test tests whether or not there is a significant difference between a value exactly two groups of observations (an ANOVA test can be used when there are more than two groups). We will be using this test to ascertain whether or not there is a significant difference in temperature when these observations are grouped by station (note that there are exactly two stations, Kentville and Greenwood).</p>
<div id="assumptions-3" class="section level4">
<h4><span class="header-section-number">6.3.1.1</span> Assumptions</h4>
<p>The t-test assumes that the two samples of data values are normally distributed and independent.</p>
</div>
<div id="test-data-1" class="section level4">
<h4><span class="header-section-number">6.3.1.2</span> Test Data</h4>
<p>A t-test requires a data frame with a column containing the values to test, and a column containing the variable to group by (usually contains strings like “group1”, “group2”, “group3”, etc.). It is often useful to keep other qualifying variables that give context to each observation, but are not required by the test. In our case, the column in <code>climate_data</code> that contains the values we are testing is <code>meantemp</code>, and the column that contains the groups is <code>station_name</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">t_test_data &lt;-<span class="st"> </span>climate_data %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(station_name, year, month, meantemp)</code></pre></div>
</div>
<div id="graphical-test-1" class="section level4">
<h4><span class="header-section-number">6.3.1.3</span> Graphical Test</h4>
<p>The graphic for an ANOVA test is a series of boxplots, with exactly two variables on the x axis. This is generated using something like <code>ggplot(my_data_frame, aes(x = group_column, y = value_column))</code> followed by <code>geom_boxplot()</code>. For the test we are about to do, the graphic looks like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(t_test_data, <span class="kw">aes</span>(<span class="dt">x =</span> station_name, <span class="dt">y =</span> meantemp)) +
<span class="st">  </span><span class="kw">geom_boxplot</span>()</code></pre></div>
<pre><code>## Warning: Removed 1 rows containing non-finite values (stat_boxplot).</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-66-1.png" width="672" /></p>
<p>Based on the graphic, you should be able to have a hunch as to whether or not one boxplot is significantly different than the other boxplot (when grouped by station, it looks like there isn’t much difference in temperature). This is important, because it will make interpreting your results more intuitive and allows you to check for errors.</p>
</div>
</div>
</div>
<div id="statistical-test-3" class="section level2">
<h2><span class="header-section-number">6.4</span> Statistical Test</h2>
<p>Performing the t-test uses a call to the <code>t.test()</code> function in the form <code>t.test(value_column ~ group_column, data = my_data_frame)</code>, and a call to the <code>tidy()</code> function in the <strong>broom</strong> package to view the results in the form of a data frame. In the case of the Kentville/Greenwood climate data, the two tests look like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(meantemp ~<span class="st"> </span>station_name, <span class="dt">data =</span> t_test_data) %&gt;%<span class="st"> </span><span class="kw">tidy</span>()</code></pre></div>
<pre><code>## # A tibble: 1 x 10
##     estimate estimate1 estimate2  statistic   p.value parameter  conf.low
##        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 0.06409574    7.4875  7.423404 0.03469596 0.9723966   92.9311 -3.604421
## # ... with 3 more variables: conf.high &lt;dbl&gt;, method &lt;fctr&gt;,
## #   alternative &lt;fctr&gt;</code></pre>
<p>Here the <code>estimate</code> column is the estimated difference between the means of the two groups, and the <code>p.value</code> column is the p-value, which represents the probability that there is no significant difference between the two groups (<em>p</em>=0.97).</p>
<div id="paired-t-test" class="section level3">
<h3><span class="header-section-number">6.4.1</span> Paired t-test</h3>
<p>Paired version of the t-test…</p>
</div>
<div id="wilcox-rank-sum-test" class="section level3">
<h3><span class="header-section-number">6.4.2</span> Wilcox Rank Sum Test</h3>
<p>The Wilcox Rank Sum Test is…</p>
</div>
<div id="mann-whitney-test" class="section level3">
<h3><span class="header-section-number">6.4.3</span> Mann-Whitney Test</h3>
<p>The Wilcox Rank Sum Test is…</p>
</div>
</div>
<div id="significant-differences-with-more-than-two-groups" class="section level2">
<h2><span class="header-section-number">6.5</span> Significant differences with more than two groups</h2>
<div id="the-anova-test" class="section level3">
<h3><span class="header-section-number">6.5.1</span> The ANOVA test</h3>
<p>The ANOVA test tests whether or not there is a significant difference between a value using two or more groups of observations (an ANOVA test when there are only two groups is identical to a t-test). We will be using this test to ascertain whether or not there is a significant difference in temperature when these observations are grouped by (1) year and (2) month.</p>
<div id="assumptions-4" class="section level4">
<h4><span class="header-section-number">6.5.1.1</span> Assumptions</h4>
<p>The ANOVA test assumes all samples of data values are normally distributed and independent.</p>
</div>
<div id="test-data-2" class="section level4">
<h4><span class="header-section-number">6.5.1.2</span> Test Data</h4>
<p>An ANOVA test requires a data frame with a column containing the values to test, and a column containing the variable to group by (usually contains strings like “group1”, “group2”, “group3”, etc.). It is often useful to keep other qualifying variables that give context to each observation, but are not required by the test. In our case, the column in <code>climate_data</code> that contains the values we are testing is <code>meantemp</code>, and the column that contains the groups is <code>year</code> for the first test, and <code>month</code> for the second.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">anova_test_data &lt;-<span class="st"> </span>climate_data %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(station_name, year, month, meantemp)</code></pre></div>
</div>
</div>
<div id="graphical-test-2" class="section level3">
<h3><span class="header-section-number">6.5.2</span> Graphical Test</h3>
<p>The graphic for an ANOVA test is a series of boxplots, with two or more variables on the x axis. This is generated using something like <code>ggplot(my_data_frame, aes(x = group_column, y = value_column))</code> followed by <code>geom_boxplot()</code>. For the two tests we are about to do, the graphics look like this (note that we are using <code>factor(year)</code> instead of just <code>year</code> because otherwise <code>ggplot</code> interprets the <code>year</code> variable as continuous, when we are using it to group data into discrete groups):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(anova_test_data, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(year), <span class="dt">y =</span> meantemp)) +
<span class="st">  </span><span class="kw">geom_boxplot</span>()</code></pre></div>
<pre><code>## Warning: Removed 1 rows containing non-finite values (stat_boxplot).</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(anova_test_data, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(month), <span class="dt">y =</span> meantemp)) +
<span class="st">  </span><span class="kw">geom_boxplot</span>()</code></pre></div>
<pre><code>## Warning: Removed 1 rows containing non-finite values (stat_boxplot).</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-70-1.png" width="672" /></p>
<p>Based on the graphic, you should be able to have a hunch as to whether or not each boxplot is significantly different than any other boxplot (when grouped by year, it looks like there isn’t much difference in temperature, but by month, there is definitely a difference). This is important, because it will make interpreting your results more intuitive and allows you to check for errors.</p>
<div id="statistical-test-4" class="section level4">
<h4><span class="header-section-number">6.5.2.1</span> Statistical Test</h4>
<p>Performing the ANOVA test uses a call to the <code>aov()</code> function in the form <code>aov(value_column ~ group_column, data = my_data_frame)</code>, and a call to the <code>tidy()</code> function in the <strong>broom</strong> package to view the results in the form of a data frame. In the case of the Kentville/Greenwood climate data, the two tests look like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">aov</span>(meantemp ~<span class="st"> </span>year, <span class="dt">data =</span> climate_data) %&gt;%<span class="st"> </span><span class="kw">tidy</span>()</code></pre></div>
<pre><code>## # A tibble: 2 x 6
##        term    df       sumsq    meansq  statistic   p.value
##       &lt;chr&gt; &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
## 1      year     1    3.482852  3.482852 0.04300005 0.8361786
## 2 Residuals    93 7532.671464 80.996467         NA        NA</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">aov</span>(meantemp ~<span class="st"> </span>month, <span class="dt">data =</span> climate_data) %&gt;%<span class="st"> </span><span class="kw">tidy</span>()</code></pre></div>
<pre><code>## # A tibble: 2 x 6
##        term    df    sumsq     meansq statistic      p.value
##       &lt;chr&gt; &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt;
## 1     month     1 1057.750 1057.75038  15.18442 0.0001837213
## 2 Residuals    93 6478.404   69.66026        NA           NA</code></pre>
<p>Generally, the only column we care about in the output is the <code>p.value</code>, which is the probability that none of the groups of values are significantly different than any others. In the case of the Kentville/Greenwood climate data, there is a significant difference in temperature among months (<em>p</em>&lt;0.001), but no significant different in temperature among years (<em>p</em>=0.83).</p>
</div>
</div>
<div id="krustal-wallis-rank-sum-test" class="section level3">
<h3><span class="header-section-number">6.5.3</span> Krustal-Wallis Rank Sum Test</h3>
<p>Krustal Wallis Test…</p>
</div>
</div>
<div id="summary-5" class="section level2">
<h2><span class="header-section-number">6.6</span> Summary</h2>
<p>Tutorial summary</p>

<div id="refs" class="references">

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="using-rstudio-projects.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/paleolimbot/r4cwrs/edit/master/06-stats.Rmd",
"text": "Edit"
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
